name: Base Checks

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  base-checks:
    runs-on: ubuntu-latest
    env:
      ASTRO_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # --- Lint / Format  ---
      - name: Prettier (format check)
        run: yarn exec prettier . --check

      - name: ESLint (lint check)
        if: ${{ hashFiles('eslint.config.*') != '' }}
        run: yarn eslint . --max-warnings=0

      # --- Type & Framework Checks ---
      - name: Astro check
        run: yarn astro check

      - name: TypeScript compile check
        if: ${{ hashFiles('tsconfig.json') != '' }}
        run: yarn tsc --noEmit
