name: Base Checks

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  base-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ASTRO_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .yarn/unplugged
            .yarn/build-state.yml
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      # --- Lint / Format  ---
      - name: Prettier (format check)
        run: yarn exec prettier . --check

      - name: ESLint (lint check)
        if: ${{ hashFiles('eslint.config.*') != '' }}
        run: yarn eslint . --max-warnings=0

      # --- Type & Framework Checks ---
      - name: Astro check
        run: yarn astro check

      - name: TypeScript compile check
        if: ${{ hashFiles('tsconfig.json') != '' }}
        run: yarn tsc --noEmit
